<?php
// Excel Export for Simran Beauty Bookings
header('Content-Type: application/vnd.ms-excel');
header('Content-Disposition: attachment; filename="simran_beauty_bookings_' . date('Y-m-d') . '.xls"');
header('Pragma: no-cache');
header('Expires: 0');

// Read bookings from JSON file
$bookings_file = 'bookings.json';
$bookings = [];

if (file_exists($bookings_file)) {
    $bookings = json_decode(file_get_contents($bookings_file), true) ?: [];
}

// Start Excel output
echo '<table border="1">';
echo '<tr style="background-color: #d4af37; color: white; font-weight: bold;">';
echo '<th>Token Number</th>';
echo '<th>Customer Name</th>';
echo '<th>Phone Number</th>';
echo '<th>Email Address</th>';
echo '<th>Service</th>';
echo '<th>Appointment Date</th>';
echo '<th>Appointment Time</th>';
echo '<th>Special Requests</th>';
echo '<th>Status</th>';
echo '<th>Booking Date/Time</th>';
echo '</tr>';

// Output booking data
foreach ($bookings as $booking) {
    echo '<tr>';
    echo '<td>' . htmlspecialchars($booking['token_number'] ?? '') . '</td>';
    echo '<td>' . htmlspecialchars($booking['name'] ?? '') . '</td>';
    echo '<td>' . htmlspecialchars($booking['phone'] ?? '') . '</td>';
    echo '<td>' . htmlspecialchars($booking['email'] ?? '') . '</td>';
    echo '<td>' . htmlspecialchars($booking['service'] ?? '') . '</td>';
    echo '<td>' . htmlspecialchars($booking['date'] ?? '') . '</td>';
    echo '<td>' . htmlspecialchars($booking['time'] ?? '') . '</td>';
    echo '<td>' . htmlspecialchars($booking['message'] ?? 'None') . '</td>';
    echo '<td style="background-color: ' . ($booking['status'] === 'confirmed' ? '#d4edda' : '#fff3cd') . ';">' . 
         htmlspecialchars(ucfirst($booking['status'] ?? 'pending')) . '</td>';
    echo '<td>' . htmlspecialchars($booking['created_at'] ?? '') . '</td>';
    echo '</tr>';
}

echo '</table>';

// Add summary at the bottom
echo '<br><br>';
echo '<table border="1">';
echo '<tr style="background-color: #f8f9fa;">';
echo '<th colspan="2">Booking Summary</th>';
echo '</tr>';
echo '<tr>';
echo '<td><strong>Total Bookings:</strong></td>';
echo '<td>' . count($bookings) . '</td>';
echo '</tr>';
echo '<tr>';
echo '<td><strong>Export Date:</strong></td>';
echo '<td>' . date('Y-m-d H:i:s') . '</td>';
echo '</tr>';
echo '<tr>';
echo '<td><strong>Generated By:</strong></td>';
echo '<td>Simran Beauty Parlour Admin Panel</td>';
echo '</tr>';
echo '</table>';
?>