<?php
// Enhanced CSV Export with All Booking Details
header('Content-Type: text/csv');
header('Content-Disposition: attachment; filename="simran_beauty_complete_bookings_' . date('Y-m-d_H-i-s') . '.csv"');
header('Pragma: no-cache');
header('Expires: 0');

// Read bookings from JSON file
$bookings_file = 'bookings.json';
$bookings = [];

if (file_exists($bookings_file)) {
    $bookings = json_decode(file_get_contents($bookings_file), true) ?: [];
}

// Sort bookings by created_at descending (newest first)
usort($bookings, function($a, $b) {
    return strtotime($b['created_at']) - strtotime($a['created_at']);
});

// Open output stream
$output = fopen('php://output', 'w');

// CSV Headers
$headers = [
    'S.No.',
    'Token Number',
    'Customer Name',
    'Phone Number',
    'Email Address',
    'Service Requested',
    'Appointment Date',
    'Appointment Time',
    'Special Requests',
    'Current Status',
    'Booking Date/Time',
    'Days Since Booking',
    'Estimated Cost (₹)',
    'Customer Type',
    'Priority Level'
];

fputcsv($output, $headers);

// Service rates for cost estimation
$service_rates = [
    'facial' => 1500,
    'haircut' => 800,
    'makeup' => 2500,
    'manicure' => 600,
    'pedicure' => 800,
    'threading' => 300,
    'waxing' => 1200,
    'massage' => 2000,
    'bridal makeup' => 5000,
    'party makeup' => 3000
];

// Output booking data
$row_count = 0;
foreach ($bookings as $booking) {
    $row_count++;
    
    // Calculate days since booking
    $booking_date = new DateTime($booking['created_at']);
    $current_date = new DateTime();
    $days_diff = $current_date->diff($booking_date)->days;
    
    // Estimate cost
    $service = strtolower($booking['service'] ?? '');
    $estimated_cost = $service_rates[$service] ?? 1000;
    
    // Determine customer type (new/returning based on phone number frequency)
    $phone_count = 0;
    foreach ($bookings as $b) {
        if ($b['phone'] === $booking['phone']) {
            $phone_count++;
        }
    }
    $customer_type = $phone_count > 1 ? 'Returning Customer' : 'New Customer';
    
    // Priority level based on service and days since booking
    $priority = 'Normal';
    if (in_array($service, ['bridal makeup', 'party makeup'])) {
        $priority = 'High';
    } elseif ($days_diff > 7) {
        $priority = 'Urgent';
    }
    
    $row = [
        $row_count,
        $booking['token_number'] ?? '',
        $booking['name'] ?? '',
        $booking['phone'] ?? '',
        $booking['email'] ?? '',
        $booking['service'] ?? '',
        $booking['date'] ?? '',
        $booking['time'] ?? '',
        $booking['message'] ?? 'No special requests',
        strtoupper($booking['status'] ?? 'PENDING'),
        $booking['created_at'] ?? '',
        $days_diff . ' days',
        $estimated_cost,
        $customer_type,
        $priority
    ];
    
    fputcsv($output, $row);
}

// Add summary statistics at the end
fputcsv($output, []); // Empty row
fputcsv($output, ['=== SUMMARY STATISTICS ===']);
fputcsv($output, ['Total Bookings', count($bookings)]);
fputcsv($output, ['Confirmed Bookings', count(array_filter($bookings, function($b) { return $b['status'] === 'confirmed'; }))]);
fputcsv($output, ['Pending Bookings', count(array_filter($bookings, function($b) { return $b['status'] === 'pending'; }))]);

// Service popularity
$service_stats = [];
foreach ($bookings as $booking) {
    $service = $booking['service'] ?? 'Unknown';
    $service_stats[$service] = ($service_stats[$service] ?? 0) + 1;
}
arsort($service_stats);

fputcsv($output, []); // Empty row
fputcsv($output, ['=== SERVICE POPULARITY ===']);
foreach ($service_stats as $service => $count) {
    $percentage = round(($count / count($bookings)) * 100, 1);
    fputcsv($output, [$service, $count . ' (' . $percentage . '%)']);
}

// Revenue estimation
$total_revenue = array_sum(array_map(function($booking) use ($service_rates) {
    $service = strtolower($booking['service'] ?? '');
    return $service_rates[$service] ?? 1000;
}, $bookings));

fputcsv($output, []); // Empty row
fputcsv($output, ['=== REVENUE ANALYSIS ===']);
fputcsv($output, ['Estimated Total Revenue', '₹' . number_format($total_revenue)]);
fputcsv($output, ['Average Revenue per Booking', '₹' . number_format($total_revenue / max(count($bookings), 1))]);

fputcsv($output, []); // Empty row
fputcsv($output, ['Export Generated On', date('Y-m-d H:i:s')]);
fputcsv($output, ['Generated By', 'Simran Beauty Parlour Admin Panel']);

fclose($output);
?>